/****  ⚠ DO NOT EDIT THIS FILE - It will be replaced for testing  ⚠   ****/

import { SafeAreaView, StyleSheet, StatusBar, Platform } from 'react-native';
import GameComponent from './GameComponent';

/* Note SafeAreaView is used to reduce the view to avoid the status bar at the top of the screen. 
   It only worked on iOS and is now deprecated but OK to use for now and saves a separate package instal.
   Hack for Android included in the sytlesheet.  */


/****  ⚠ DO NOT EDIT THIS FILE - It will be replaced for testing  ⚠   ****/
export default function App() {
  return (
    <SafeAreaView style={styles.wholepage}>
       <GameComponent/> 
    </SafeAreaView>
  );
}

/****  ⚠ DO NOT EDIT THIS FILE - It will be replaced for testing  ⚠   ****/
const styles = StyleSheet.create({
  wholepage: {
    flex: 1,
    paddingTop: Platform.OS === 'android'? StatusBar.currentHeight : 0,
    backgroundColor: '#fff',
  }
});

/****  ⚠ DO NOT EDIT THIS FILE - It will be replaced for testing  ⚠   ****/

